export { default as Navigation } from './Navigation'
export { default as Main } from './Main'
export { default as Welcome } from './Welcome'
export { default as About } from './About'
export { default as Contact } from './Contact'
